name: 'DeepL Translation Verifier'
description: 'Checks translations in files against DeepL API'
author: 'S-MpAI'
inputs:
  translation-file-patterns:
    description: 'Comma-separated list of file patterns to check'
    required: false
    default: 'Translations.txt,.i18n'
  source-lang:
    description: 'Source language code'
    required: false
    default: 'EN'
  target-lang:
    description: 'Target language code'
    required: false
    default: 'RU'
runs:
  using: 'composite'  # Используем composite action вместо node16
  steps:
    - name: Install dependencies
      run: npm install
      shell: bash
    - name: Run translation check
      run: node check_translations.js
      shell: bash
outputs:
  status:
    description: 'Result of the translation check (success or failure)'
branding:
  icon: 'check'
  color: 'blue'
